// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Message struct {
	ID        int64
	RoomID    int64
	UserID    int64
	Body      string
	CreatedAt sql.NullTime
}

type Migration struct {
	Filename  string
	AppliedAt sql.NullTime
}

type Room struct {
	ID        int64
	Name      string
	CreatorID int64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type RoomMembership struct {
	RoomID   int64
	UserID   int64
	JoinedAt sql.NullTime
}

type User struct {
	ID        int64
	GithubUid int64
	Login     string
	AvatarUrl sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
